Repository webcomponents/polyfills, pull requests merged in 2021-08, with the labels that each got.

#465 Update changelogs for release.
  packages/custom-elements/CHANGELOG.md
  packages/html-imports/CHANGELOG.md
  packages/scoped-custom-element-registry/CHANGELOG.md
  packages/shadycss/CHANGELOG.md
  packages/shadydom/CHANGELOG.md
  packages/template/CHANGELOG.md
  packages/url/CHANGELOG.md
  packages/webcomponentsjs/CHANGELOG.md
Labels: cla: yes

#466 Manually update versions of local packages in tests package.
  packages/tests/package.json
Labels: Skip Changelog, cla: yes

#467 Upstream internal changes to 'style-settings.js'.
  packages/shadycss/CHANGELOG.md
  packages/shadycss/src/style-settings.js
Labels: cla: yes

#472 Adds an opt-out for polyfilling `element(s)FromPoint` on document
  packages/shadydom/CHANGELOG.md
  packages/shadydom/src/patches/DocumentOrShadowRoot.js
  packages/tests/shadydom/shady.html
Labels: cla: yes

#469 Allow event listener options to be specified with a function in addition to an object or boolean
  packages/shadydom/CHANGELOG.md
  packages/shadydom/src/patch-events.js
  packages/tests/shadydom/shady.html
  packages/tests/webcomponentsjs_/event-listener-options.html
  packages/tests/webcomponentsjs_/runner.html
  packages/webcomponentsjs/CHANGELOG.md
  packages/webcomponentsjs/src/entrypoints/webcomponents-pf_dom-index.js
  packages/webcomponentsjs/ts_src/platform/event-listener-options.ts
Labels: cla: no

#474 Fix a few links in the changelogs.
  packages/shadydom/CHANGELOG.md
  packages/webcomponentsjs/CHANGELOG.md
Labels: cla: yes

#473 Add type annotations for JSCompiler to `eventPhase` property descriptor.
  packages/shadydom/CHANGELOG.md
  packages/shadydom/src/patch-events.js
Labels: cla: yes
