Repository webcomponents/polyfills, pull requests merged in 2021-02, with the labels that each got.

#428 Update google-closure-compiler.
  package-lock.json
  package.json
  packages/custom-elements/gulpfile.js
  packages/formdata-event/gulpfile.js
  packages/html-imports/gulpfile.js
  packages/shady-css-scoped-element/gulpfile.js
  packages/shadycss/gulpfile.js
  packages/template/gulpfile.js
  packages/url/gulpfile.js
  packages/webcomponentsjs/gulpfile.js
Labels: Skip Changelog, cla: yes

#429 Add a build step, update test / demo files, update @web/test-runner packages.
  package-lock.json
  package.json
  packages/scoped-custom-element-registry/demo/index.html
  packages/scoped-custom-element-registry/gulpfile.js
  packages/scoped-custom-element-registry/package.json
  packages/scoped-custom-element-registry/src/scoped-custom-element-registry.js
  packages/scoped-custom-element-registry/test/Element.test.html
  packages/scoped-custom-element-registry/test/ShadowRoot.test.html
  packages/scoped-custom-element-registry/test/global-registry.test.html
  packages/scoped-custom-element-registry/test/scoped-registry.test.html
Labels: Package: scoped-custom-element-registry, cla: yes

#431 Add a changelog entry for the first prerelease of the Scoped CustomElementRegistry polyfill.
  packages/scoped-custom-element-registry/CHANGELOG.md
Labels: cla: yes

#432 Fix the 'homepage' field in the scoped-custom-element-registry package.json
  packages/scoped-custom-element-registry/package.json
Labels: Package: scoped-custom-element-registry, Skip Changelog, cla: yes

#433 Upstream cl/345169174: Fix calls to XMLHttpRequest#getResponseHeader to accept null as a return value.
  packages/html-imports/CHANGELOG.md
  packages/html-imports/gulpfile.js
  packages/html-imports/src/html-imports.js
  packages/tests/html-imports/html/es-module.html
Labels: cla: yes

#434 fix(shadydom): shadycss package url in README
  packages/shadydom/README.md
Labels: cla: yes
